server:
  port: 8085


spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transactionservice
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      type: trace
  flyway:
    url: jdbc:postgresql://localhost:5432/transactionservice
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: postgres
    validate-on-migrate: false

